name:                math-programming-glpk
version:             0.1.0.0
github:              "prsteele/math-programming-glpk"
license:             BSD3
author:              "Patrick Steele"
maintainer:          "steele.pat@gmail.com"
copyright:           "2018 Patrick Steele"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            A GLPK backend to the math-programming library.
category:            Math

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/prsteele/math-programming-glpk#readme>

dependencies:
  - base >= 4.7 && < 5
  - glpk-hs >= 0.1.0.0 && < 0.2
  - mtl >= 2.2.2 && < 2.3
  - containers >= 0.5.11 && < 0.6
  - math-programming

library:
  ghc-options:
    - -Wall
  source-dirs: src

executables:
  main-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
      - -Wall
    extra-libraries:
      - glpk
    dependencies:
      - math-programming-glpk

tests:
  math-programming-glpk-test:
    main:                Driver.hs
    source-dirs:         test
    ghc-options:
      - -Wall
    extra-libraries:
      - glpk
    dependencies:
      - math-programming-glpk
      - math-programming-api-tests
      - tasty >= 1.1.0.2 && < 1.2
      - tasty-discover >= 4.2.0 && < 4.3
      - tasty-hunit >= 0.10.0.1 && < 0.11
