name:                math-programming-glpk
version:             0.4.1
github:              "prsteele/math-programming-glpk"
license:             BSD3
author:              "Patrick Steele"
maintainer:          "steele.pat@gmail.com"
copyright:           "2018 Patrick Steele"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            A GLPK backend to the math-programming library.
category:            Math

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/prsteele/math-programming-glpk#readme>

dependencies:
  - base >= 4.7 && < 5
  - glpk-headers >= 0.4.0 && < 0.5
  - mtl
  - containers
  - math-programming >= 0.4.0 && < 0.5
  - text

library:
  ghc-options:
    - -Wall
  source-dirs: src

tests:
  math-programming-glpk-test:
    main:                Driver.hs
    source-dirs:         test
    ghc-options:
      - -Wall
    extra-libraries:
      - glpk
    dependencies:
      - math-programming-glpk
      - math-programming-tests >= 0.4.0 && < 0.5
      - tasty
      - tasty-discover
      - tasty-hunit
